import { Utensils, Coffee, Salad, Sandwich, Sun, Droplets, IceCreamBowl } from 'lucide-react';
import type { Category } from './types/foodmenu/menu';



const categories: Category[] = [
  // ------------------------
  // Grills
  // ------------------------
  {
    id: "grills",
    name: "Grills",
    icon: Utensils,
    products: [
      {
        id: "beef-quesadilla",
        name: "Beef Quesadilla Por Favor",
        weight: "",
        price: "Rs. 2300",
        description: "Freshly grilled beef & vibrant, nutrient-packed veggies wrapped in wholesome Atta flour quesadilla, complemented by a luscious avocado feta pairing",
        image: "/noimage.png",
        nutrition: {
          fat: "50.5g",
          protein: "41.1g",
          carbs: "59.2g",
          calories: "929",
        },
        tags: [
          { label: "High-Protein", icon: "💪" },
          { label: "Wholesome", icon: "🌾" },
        ],
        bgColor: "from-amber-800 via-orange-700 to-red-700",
        accentColor: "bg-orange-600",
      },
      {
        id: "chicken-quesadilla",
        name: "Chicken Quesadilla Por Favor",
        weight: "",
        price: "Rs. 2400",
        description: "Freshly grilled tender chicken & vibrant, nutrient-packed veggies wrapped in wholesome Atta flour quesadilla, complemented by a luscious avocado feta pairing",
        image: "/noimage.png",
        nutrition: {
          fat: "28.4g",
          protein: "33.3g",
          carbs: "62.3g",
          calories: "715",
        },
        tags: [
          { label: "High-Protein", icon: "💪" },
          { label: "Lean", icon: "🏃" },
        ],
        bgColor: "from-yellow-600 via-orange-500 to-amber-600",
        accentColor: "bg-yellow-500",
      },
      {
        id: "prawn-quesadilla",
        name: "Prawn Quesadilla Por Favor",
        weight: "",
        price: "Rs. 2500",
        description: "Freshly grilled garlic prawns & vibrant, nutrient-packed veggies wrapped in wholesome Atta flour quesadilla, complemented by a luscious avocado feta pairing",
        image: "/noimage.png",
        nutrition: {
          fat: "40.3g",
          protein: "50.9g",
          carbs: "34.9g",
          calories: "743",
        },
        tags: [
          { label: "Seafood", icon: "🦐" },
          { label: "High-Protein", icon: "💪" },
          { label: "Omega-3", icon: "🐟" },
        ],
        bgColor: "from-orange-500 via-pink-500 to-red-500",
        accentColor: "bg-pink-500",
      },
      {
        id: "omega-salmon",
        name: "Oh My....OMEGA! Salmon",
        weight: "",
        price: "Rs. 3800",
        description: "Perfectly baked Norwegian salmon fillet, crowned with a tantalizing citrus orange compote on a bed of luxuriously creamy avocado hollandaise. Accompanied by roasted sweet potato wedges and a refreshing crisp garden salad",
        image: "/noimage.png",
        nutrition: {
          fat: "40.3g",
          protein: "50.9g",
          carbs: "34.9g",
          calories: "743",
        },
        tags: [
          { label: "Premium", icon: "⭐" },
          { label: "Omega-3", icon: "🐟" },
          { label: "Heart-Healthy", icon: "❤️" },
        ],
        bgColor: "from-orange-600 via-salmon-500 to-pink-600",
        accentColor: "bg-salmon-500",
      },
      {
        id: "power-steak",
        name: "Power Steak O'clock Heart Healthy",
        weight: "",
        price: "Rs. 3400",
        description: "Tender, flavorful roasted Beef Steak paired with creamy green pea puree, savory eggplant relish, served with golden-baked baby potatoes, fresh crisp garden salad and roasted garlic",
        image: "/noimage.png",
        nutrition: {
          fat: "31g",
          protein: "70.2g",
          carbs: "39.3g",
          calories: "731",
        },
        tags: [
          { label: "High-Protein", icon: "💪" },
          { label: "Heart-Healthy", icon: "❤️" },
          { label: "Iron-Rich", icon: "🔴" },
        ],
        bgColor: "from-red-800 via-red-700 to-amber-700",
        accentColor: "bg-red-700",
      },
      {
        id: "fin-tastic-barramundi",
        name: "Fin-Tastic Barramundi",
        weight: "",
        price: "Rs. 3900",
        description: "A succulent Barramundi fish fillet, kissed by the grill, crowned with cherry tomatoes and basil compote. Served alongside baked baby potatoes and a crisp green salad",
        image: "/noimage.png",
        nutrition: {
          fat: "16.7g",
          protein: "48.7g",
          carbs: "40.4g",
          calories: "510",
        },
        tags: [
          { label: "Lean Fish", icon: "🐟" },
          { label: "Low-Fat", icon: "💚" },
          { label: "High-Protein", icon: "💪" },
        ],
        bgColor: "from-blue-600 via-teal-600 to-green-600",
        accentColor: "bg-teal-600",
      },
      {
        id: "honey-mustard-chicken",
        name: "Honey Mustard Chicken",
        weight: "",
        price: "Rs. 1900",
        description: "Succulent baked chicken, marinated in a rich honey mustard blend, delivering the perfect balance of sweet and tangy. Topped with a vibrant pineapple & watermelon salsa and drizzled with our signature honey mustard sauce. Served alongside golden roasted sweet potato wedges and a refreshing crisp green salad",
        image: "/noimage.png",
        nutrition: {
          fat: "15.5g",
          protein: "57.4g",
          carbs: "56.9g",
          calories: "648",
        },
        tags: [
          { label: "Sweet & Tangy", icon: "🍯" },
          { label: "Lean Protein", icon: "🐔" },
        ],
        bgColor: "from-amber-500 via-yellow-500 to-orange-500",
        accentColor: "bg-yellow-500",
      },
      {
        id: "thai-spiced-chicken",
        name: "Thai Spiced Chicken",
        weight: "",
        price: "Rs. 1900",
        description: "Succulent chicken baked to perfection in our signature Thai-spiced marinade, bursting with bold, exotic flavor. Drizzled with a vibrant cilantro dressing and topped with a juicy, tropical pineapple & watermelon salsa that delivers a sweet-and-spicy punch. Served alongside velvety sweet potato mash and a crisp green salad",
        image: "/noimage.png",
        nutrition: {
          fat: "36.4g",
          protein: "76.5g",
          carbs: "110.2g",
          calories: "1105",
        },
        tags: [
          { label: "Spicy", icon: "🌶️" },
          { label: "Exotic", icon: "🌏" },
          { label: "High-Protein", icon: "💪" },
        ],
        bgColor: "from-red-600 via-orange-600 to-yellow-600",
        accentColor: "bg-orange-600",
      },
      {
        id: "coconut-chicken",
        name: "Vitamin Rich Coconut Chicken",
        weight: "",
        price: "Rs. 2400",
        description: "Tender oven-baked chicken coated in a nutrient-dense blend of coconut and kurakkan breadcrumbs, offering a warm, wholesome crunch. Finished with a fragrant lemongrass sauce and topped with finely sliced green chillies for a subtle kick. Served with velvety sweet potato mash and a crisp green salad",
        image: "/noimage.png",
        nutrition: {
          fat: "22.7g",
          protein: "80.8g",
          carbs: "84.50g",
          calories: "938",
        },
        tags: [
          { label: "Coconut", icon: "🥥" },
          { label: "Vitamin-Rich", icon: "💊" },
          { label: "Crunchy", icon: "🥖" },
        ],
        bgColor: "from-amber-600 via-orange-500 to-yellow-500",
        accentColor: "bg-amber-500",
      },
      {
        id: "vegetable-shepherds-pie",
        name: "Vegetable Shepherd's Pie",
        weight: "",
        price: "Rs. 1100",
        description: "A wholesome, plant-based twist on a classic — hearty chickpeas, red kidney beans, cauliflower, carrot, and spinach, crowned with a creamy sweet potato mash",
        image: "/noimage.png",
        nutrition: {
          fat: "9.4g",
          protein: "27.0g",
          carbs: "78.4g",
          calories: "562",
        },
        tags: [
          { label: "Vegetarian", icon: "🌱" },
          { label: "Plant-Based", icon: "🥕" },
          { label: "High-Fiber", icon: "🌾" },
        ],
        bgColor: "from-green-700 via-emerald-600 to-teal-600",
        accentColor: "bg-green-600",
      },
    ],
  },
  // ------------------------
  // Rice Bowls
  // ------------------------
  {
    id: "rice-bowls",
    name: "Rice Bowls",
    icon: IceCreamBowl,
    products: [
      {
        id: "chicken-rice-bowl",
        name: "Chicken Rice Bowl",
        weight: "",
        price: "Rs. 1400",
        description: "Baked chicken, complemented by a golden fried egg and a vibrant medley of crunchy peanuts, paired with the vegetable of the day. All of this is crowned with a flavorful coconut sambol and served over a bed of fragrant steamed garlic basmati rice",
        image: "/noimage.png",
        nutrition: {
          fat: "26.5g",
          protein: "23.8g",
          carbs: "37.7g",
          calories: "505",
        },
        tags: [
          { label: "Comfort Food", icon: "🍚" },
          { label: "Coconut", icon: "🥥" },
        ],
        bgColor: "from-yellow-600 via-amber-500 to-orange-500",
        accentColor: "bg-amber-500",
      },
      {
        id: "beef-rice-bowl",
        name: "Beef Rice Bowl",
        weight: "",
        price: "Rs. 1500",
        description: "Roast Beef Slices, complemented by a golden fried egg and a vibrant medley of crunchy peanuts, paired with the vegetable of the day. All of this is crowned with a flavorful coconut sambol and served over a bed of fragrant steamed garlic basmati rice",
        image: "/noimage.png",
        nutrition: {
          fat: "26.2g",
          protein: "28.4g",
          carbs: "37.0g",
          calories: "512",
        },
        tags: [
          { label: "Hearty", icon: "🥩" },
          { label: "Protein-Rich", icon: "💪" },
        ],
        bgColor: "from-red-700 via-amber-600 to-orange-600",
        accentColor: "bg-red-600",
      },
      {
        id: "prawn-rice-bowl",
        name: "Prawn Rice Bowl",
        weight: "",
        price: "Rs. 1700",
        description: "Garlic Prawns, complemented by a golden fried egg and a vibrant medley of crunchy peanuts, paired with the vegetable of the day. All of this is crowned with a flavorful coconut sambol and served over a bed of fragrant steamed garlic basmati rice",
        image: "/noimage.png",
        nutrition: {
          fat: "24.5g",
          protein: "25.7g",
          carbs: "36.6g",
          calories: "484",
        },
        tags: [
          { label: "Seafood", icon: "🦐" },
          { label: "Garlic", icon: "🧄" },
        ],
        bgColor: "from-orange-600 via-pink-500 to-red-500",
        accentColor: "bg-pink-500",
      },
    ],
  },
  // ------------------------
  // Salad Bowls
  // ------------------------
  {
    id: "salad-bowls",
    name: "Salad Bowls",
    icon: Salad,
    products: [
      {
        id: "liver-cleansing-salad",
        name: "Liver Cleansing Salad",
        weight: "",
        price: "Rs. 1950",
        description: "Revitalize with our nutrient-packed salad featuring vibrant beetroot, green lettuce, creamy feta cheese, juicy orange slices, ripe avocado, a boiled egg, & a sprinkle of pumpkin seeds. Served alongside multi-seed dark brown bread for a wholesome crunch",
        image: "/noimage.png",
        nutrition: {
          fat: "30.6g",
          protein: "18.4g",
          carbs: "31.9g",
          calories: "784",
        },
        tags: [
          { label: "Detox", icon: "🧹" },
          { label: "Nutrient-Dense", icon: "💎" },
          { label: "Antioxidants", icon: "🍇" },
        ],
        bgColor: "from-purple-700 via-red-600 to-pink-600",
        accentColor: "bg-purple-600",
      },
      {
        id: "green-salad",
        name: "Green Salad",
        weight: "",
        price: "Rs. 1400",
        description: "A vibrant garden-fresh mix of green and crisp lettuces, crunchy Japanese cucumber, juicy tomatoes, and zesty green bell pepper — tossed with bold black olives and delicate onion rings. Drizzled with our signature Chef's salad dressing and finished with pomegranate seeds and toasted multigrain bread for a wholesome crunch",
        image: "/noimage.png",
        nutrition: {
          fat: "11.8g",
          protein: "15.9g",
          carbs: "59.9g",
          calories: "447",
        },
        tags: [
          { label: "Fresh", icon: "🥬" },
          { label: "Low-Calorie", icon: "📉" },
          { label: "Garden-Fresh", icon: "🌿" },
        ],
        bgColor: "from-green-600 via-emerald-500 to-teal-500",
        accentColor: "bg-green-500",
      },
      {
        id: "muscle-builder-roast-beef",
        name: "Muscle Builder Salad - Roast Beef",
        weight: "",
        price: "Rs. 1800",
        description: "A dynamic blend of mixed lettuce, colorful bell peppers, crisp green apple, hearty quinoa, flavorful onions, sun-dried tomatoes, and protein-packed roast beef, all drizzled with a kick of green sriracha",
        image: "/noimage.png",
        nutrition: {
          fat: "5.9g",
          protein: "34.9g",
          carbs: "29.8g",
          calories: "317",
        },
        tags: [
          { label: "High-Protein", icon: "💪" },
          { label: "Quinoa", icon: "🌾" },
          { label: "Muscle-Building", icon: "🏋️" },
        ],
        bgColor: "from-red-700 via-orange-600 to-amber-600",
        accentColor: "bg-red-600",
      },
      {
        id: "muscle-builder-chicken",
        name: "Muscle Builder Salad - Baked Chicken",
        weight: "",
        price: "Rs. 1600",
        description: "A dynamic blend of mixed lettuce, colorful bell peppers, crisp green apple, hearty quinoa, flavorful onions, sun-dried tomatoes, and protein-packed baked chicken, all drizzled with a kick of green sriracha",
        image: "/noimage.png",
        nutrition: {
          fat: "4.6g",
          protein: "36.6g",
          carbs: "29.8g",
          calories: "308",
        },
        tags: [
          { label: "High-Protein", icon: "💪" },
          { label: "Lean", icon: "🏃" },
          { label: "Quinoa", icon: "🌾" },
        ],
        bgColor: "from-yellow-600 via-orange-500 to-red-500",
        accentColor: "bg-orange-500",
      },
      {
        id: "muscle-builder-prawns",
        name: "Muscle Builder Salad - Garlic Prawns",
        weight: "",
        price: "Rs. 1800",
        description: "A dynamic blend of mixed lettuce, colorful bell peppers, crisp green apple, hearty quinoa, flavorful onions, sun-dried tomatoes, and protein-packed garlic prawns, all drizzled with a kick of green sriracha",
        image: "/noimage.png",
        nutrition: {
          fat: "4.5g",
          protein: "20.2g",
          carbs: "34.2g",
          calories: "263",
        },
        tags: [
          { label: "Seafood", icon: "🦐" },
          { label: "High-Protein", icon: "💪" },
          { label: "Low-Calorie", icon: "📉" },
        ],
        bgColor: "from-orange-600 via-pink-500 to-red-500",
        accentColor: "bg-pink-500",
      },
    ],
  },
  // ------------------------
  // Sandwiches
  // ------------------------
  {
    id: "sandwiches",
    name: "Sandwiches",
    icon: Sandwich,
    products: [
      {
        id: "roast-beef-sandwich",
        name: "Beefed up! Roast Beef Kurakkan Roast Paan Sandwich",
        weight: "",
        price: "Rs. 1700",
        description: "Succulent roast beef, creamy feta, and sweet caramelized onions with zesty sun-dried tomato pesto, served on Kurakkan Roast Paan",
        image: "/noimage.png",
        nutrition: {
          fat: "5.1g",
          protein: "32.3g",
          carbs: "7.4g",
          calories: "546",
        },
        tags: [
          { label: "Kurakkan Bread", icon: "🍞" },
          { label: "High-Protein", icon: "💪" },
        ],
        bgColor: "from-amber-700 via-red-600 to-orange-600",
        accentColor: "bg-amber-600",
      },
      {
        id: "honey-mustard-chicken-sandwich",
        name: "Honey Mustard Chicken Kurakkan Roast Paan Sandwich",
        weight: "",
        price: "Rs. 900",
        description: "Oven-baked honey mustard chicken with creamy garlic curd paste, served on hearty Kurakkan Roast Paan",
        image: "/noimage.png",
        nutrition: {
          fat: "3.5g",
          protein: "14.4g",
          carbs: "3.2g",
          calories: "441",
        },
        tags: [
          { label: "Sweet & Tangy", icon: "🍯" },
          { label: "Kurakkan Bread", icon: "🍞" },
        ],
        bgColor: "from-yellow-600 via-amber-500 to-orange-500",
        accentColor: "bg-yellow-500",
      },
      {
        id: "thai-spiced-chicken-sandwich",
        name: "Thai Spiced Chicken Kurakkan Roast Paan Sandwich",
        weight: "",
        price: "Rs. 900",
        description: "Thai-spiced chicken with creamy garlic curd paste, served on hearty Kurakkan Roast Paan",
        image: "/noimage.png",
        nutrition: {
          fat: "3.6g",
          protein: "14.5g",
          carbs: "3.1g",
          calories: "442",
        },
        tags: [
          { label: "Spicy", icon: "🌶️" },
          { label: "Thai-Inspired", icon: "🌏" },
        ],
        bgColor: "from-red-600 via-orange-500 to-yellow-500",
        accentColor: "bg-orange-500",
      },
      {
        id: "kochchi-spiced-chicken-sandwich",
        name: "Kochchi Spiced Chicken Kurakkan Roast Paan Sandwich",
        weight: "",
        price: "Rs. 1100",
        description: "Juicy chicken breast marinated in a fiery Kochchi spice blend, layered with creamy garlic curd and zesty green Sriracha sauce on hearty Kurakkan Roast Paan",
        image: "/noimage.png",
        nutrition: {
          fat: "14.0g",
          protein: "21.2g",
          carbs: "4.1g",
          calories: "562",
        },
        tags: [
          { label: "Spicy", icon: "🌶️" },
          { label: "Sri Lankan", icon: "🇱🇰" },
        ],
        bgColor: "from-red-700 via-orange-600 to-yellow-600",
        accentColor: "bg-red-600",
      },
      {
        id: "grilled-veggie-sandwich",
        name: "Grilled Veggie Blast Kurakkan Roast Paan Sandwich",
        weight: "",
        price: "Rs. 1000",
        description: "A medley of grilled bell peppers, zucchini, and eggplant with basil pesto, served on hearty Kurakkan Roast Paan",
        image: "/noimage.png",
        nutrition: {
          fat: "15.1g",
          protein: "10.7g",
          carbs: "30.1g",
          calories: "721",
        },
        tags: [
          { label: "Vegetarian", icon: "🌱" },
          { label: "Grilled", icon: "🔥" },
        ],
        bgColor: "from-green-600 via-yellow-500 to-orange-500",
        accentColor: "bg-green-500",
      },
      {
        id: "egg-coconut-sambol-sandwich",
        name: "Egg & Coconut Sambol Kurakkan Roast Paan Sandwich",
        weight: "",
        price: "Rs. 850",
        description: "A double-fried egg paired with mouthwatering Sri Lankan coconut sambol and creamy garlic curd paste, served on hearty Kurakkan Roast Paan",
        image: "/noimage.png",
        nutrition: {
          fat: "19.1g",
          protein: "7.0g",
          carbs: "6.74g",
          calories: "567",
        },
        tags: [
          { label: "Sri Lankan", icon: "🇱🇰" },
          { label: "Coconut", icon: "🥥" },
          { label: "Vegetarian", icon: "🌱" },
        ],
        bgColor: "from-yellow-600 via-amber-500 to-orange-500",
        accentColor: "bg-amber-500",
      },
    ],
  },
  // ------------------------
  // Juices
  // ------------------------
  {
    id: "juices",
    name: "Juices",
    icon: Droplets,
    products: [
      {
        id: "pineapple-pump",
        name: "Pineapple Pump",
        weight: "",
        price: "Rs. 700",
        description: "Pineapple & Honey",
        image: "/noimage.png",
        nutrition: {
          fat: "0.1g",
          protein: "0.1g",
          carbs: "9.8g",
          calories: "38",
        },
        tags: [
          { label: "Natural", icon: "🍍" },
          { label: "Vitamin C", icon: "🍊" },
        ],
        bgColor: "from-yellow-400 via-orange-400 to-amber-500",
        accentColor: "bg-yellow-400",
      },
      {
        id: "energizer",
        name: "Energizer",
        weight: "",
        price: "Rs. 1450",
        description: "Beetroot, Apple, Carrot, Mint",
        image: "/noimage.png",
        nutrition: {
          fat: "1.5g",
          protein: "8.0g",
          carbs: "53.6g",
          calories: "320",
        },
        tags: [
          { label: "Energy Boost", icon: "⚡" },
          { label: "Antioxidants", icon: "🍇" },
          { label: "Detox", icon: "🧹" },
        ],
        bgColor: "from-purple-600 via-red-500 to-orange-500",
        accentColor: "bg-purple-500",
      },
      {
        id: "glow-booster",
        name: "Glow Booster",
        weight: "",
        price: "Rs. 1600",
        description: "Carrot, Oranges",
        image: "/noimage.png",
        nutrition: {
          fat: "0.7g",
          protein: "3.3g",
          carbs: "33.6g",
          calories: "177",
        },
        tags: [
          { label: "Vitamin A", icon: "🥕" },
          { label: "Skin Health", icon: "✨" },
        ],
        bgColor: "from-orange-500 via-amber-500 to-yellow-500",
        accentColor: "bg-orange-500",
      },
      {
        id: "energy-flow",
        name: "Energy Flow",
        weight: "",
        price: "Rs. 700",
        description: "Pineapple, Mango, Spinach, Lime, Apple",
        image: "/noimage.png",
        nutrition: {
          fat: "0.8g",
          protein: "2.7g",
          carbs: "21.1g",
          calories: "102",
        },
        tags: [
          { label: "Green Juice", icon: "🌿" },
          { label: "Energy", icon: "⚡" },
        ],
        bgColor: "from-green-500 via-yellow-400 to-orange-400",
        accentColor: "bg-green-500",
      },
    ],
  },
  // ------------------------
  // Smoothies
  // ------------------------
  {
    id: "smoothies",
    name: "Smoothies",
    icon: Droplets,
    products: [
      {
        id: "energetic-banana-oatmeal",
        name: "Energetic Banana Oatmeal",
        weight: "",
        price: "Rs. 1100",
        description: "Banana, Curd, Oats, Almonds, Milk",
        image: "/noimage.png",
        nutrition: {
          fat: "8.7g",
          protein: "10.2g",
          carbs: "61.1g",
          calories: "373",
        },
        tags: [
          { label: "Protein-Rich", icon: "💪" },
          { label: "Fiber", icon: "🌾" },
        ],
        bgColor: "from-yellow-500 via-amber-400 to-orange-400",
        accentColor: "bg-yellow-500",
      },
      {
        id: "superfood-bliss",
        name: "Superfood Bliss",
        weight: "",
        price: "Rs. 1300",
        description: "Mango, Banana, Oats, Chia Seeds, Milk",
        image: "/noimage.png",
        nutrition: {
          fat: "28.1g",
          protein: "9.6g",
          carbs: "43.3g",
          calories: "486",
        },
        tags: [
          { label: "Superfood", icon: "🌟" },
          { label: "Chia Seeds", icon: "🌱" },
          { label: "Omega-3", icon: "🐟" },
        ],
        bgColor: "from-yellow-500 via-orange-400 to-pink-400",
        accentColor: "bg-orange-400",
      },
      {
        id: "passionade",
        name: "Passionade",
        weight: "",
        price: "Rs. 1200",
        description: "Mango, Banana, Passionfruit, Curd",
        image: "/noimage.png",
        nutrition: {
          fat: "3.1g",
          protein: "4.8g",
          carbs: "43.2g",
          calories: "223",
        },
        tags: [
          { label: "Tropical", icon: "🌴" },
          { label: "Vitamin C", icon: "🍊" },
        ],
        bgColor: "from-yellow-400 via-orange-400 to-pink-400",
        accentColor: "bg-yellow-400",
      },
      {
        id: "flex-and-city",
        name: "Flex & the City",
        weight: "",
        price: "Rs. 1200",
        description: "Mango, Banana, Passionfruit, Curd",
        image: "/noimage.png",
        nutrition: {
          fat: "15.9g",
          protein: "10.7g",
          carbs: "31.6g",
          calories: "307",
        },
        tags: [
          { label: "Tropical", icon: "🌴" },
          { label: "Creamy", icon: "🥛" },
        ],
        bgColor: "from-yellow-400 via-orange-400 to-pink-400",
        accentColor: "bg-yellow-400",
      },
    ],
  },
  // ------------------------
  // Coffee & Tea
  // ------------------------
  {
    id: "coffee-tea",
    name: "Coffee & Tea",
    icon: Coffee,
    products: [
      {
        id: "cafe-americano",
        name: "Café Americano",
        weight: "",
        price: "Rs. 400",
        description: "Classic black coffee",
        image: "/noimage.png",
        nutrition: {
          fat: "0.0g",
          protein: "0.0g",
          carbs: "0.0g",
          calories: "0",
        },
        tags: [
          { label: "Zero Calories", icon: "📉" },
          { label: "Caffeine", icon: "☕" },
        ],
        bgColor: "from-amber-800 via-amber-700 to-yellow-700",
        accentColor: "bg-amber-700",
      },
      {
        id: "cappuccino",
        name: "Cappuccino",
        weight: "",
        price: "Rs. 500",
        description: "Espresso with steamed milk foam",
        image: "/noimage.png",
        nutrition: {
          fat: "3.3g",
          protein: "3.2g",
          carbs: "4.8g",
          calories: "61",
        },
        tags: [
          { label: "Creamy", icon: "🥛" },
          { label: "Caffeine", icon: "☕" },
        ],
        bgColor: "from-amber-600 via-yellow-600 to-orange-500",
        accentColor: "bg-amber-600",
      },
      {
        id: "milk-tea",
        name: "Milk Tea",
        weight: "",
        price: "Rs. 500",
        description: "Traditional milk tea",
        image: "/noimage.png",
        nutrition: {
          fat: "4.8g",
          protein: "5.0g",
          carbs: "19.9g",
          calories: "138",
        },
        tags: [
          { label: "Traditional", icon: "🫖" },
          { label: "Comforting", icon: "☕" },
        ],
        bgColor: "from-amber-700 via-orange-600 to-red-500",
        accentColor: "bg-amber-600",
      },
      {
        id: "green-tea",
        name: "Green Tea",
        weight: "",
        price: "Rs. 400",
        description: "Antioxidant-rich green tea",
        image: "/noimage.png",
        nutrition: {
          fat: "0.0g",
          protein: "0.5g",
          carbs: "0.0g",
          calories: "2",
        },
        tags: [
          { label: "Antioxidants", icon: "🍃" },
          { label: "Healthy", icon: "💚" },
        ],
        bgColor: "from-green-600 via-emerald-500 to-teal-500",
        accentColor: "bg-green-500",
      },
      {
        id: "anti-aging-miracle",
        name: "Anti Aging Miracle",
        weight: "",
        price: "Rs. 400",
        description: "Butterfly Pea Flower Tea",
        image: "/noimage.png",
        nutrition: {
          fat: "0.0g",
          protein: "0.0g",
          carbs: "0.0g",
          calories: "0",
        },
        tags: [
          { label: "Anti-Aging", icon: "✨" },
          { label: "Natural", icon: "🌸" },
        ],
        bgColor: "from-blue-600 via-purple-500 to-pink-500",
        accentColor: "bg-purple-500",
      },
      {
        id: "serenity-cup",
        name: "Serenity in a Cup",
        weight: "",
        price: "Rs. 400",
        description: "Blue Lotus Flower Tea",
        image: "/noimage.png",
        nutrition: {
          fat: "0.0g",
          protein: "0.0g",
          carbs: "2.0g",
          calories: "0",
        },
        tags: [
          { label: "Calming", icon: "🧘" },
          { label: "Relaxing", icon: "💙" },
        ],
        bgColor: "from-blue-500 via-indigo-500 to-purple-500",
        accentColor: "bg-blue-500",
      },
      {
        id: "hibiscus-detox",
        name: "Hibiscus Detox Delight",
        weight: "",
        price: "Rs. 400",
        description: "Hibiscus Flower Tea",
        image: "/noimage.png",
        nutrition: {
          fat: "0.0g",
          protein: "0.0g",
          carbs: "0.5g",
          calories: "0",
        },
        tags: [
          { label: "Detox", icon: "🧹" },
          { label: "Floral", icon: "🌺" },
        ],
        bgColor: "from-pink-600 via-rose-500 to-red-500",
        accentColor: "bg-pink-500",
      },
    ],
  },
  // ------------------------
  // Desserts
  // ------------------------
  {
    id: "desserts",
    name: "Desserts",
    icon: Sun,
    products: [
      {
        id: "dark-chocolate-melt",
        name: "Heavenly Dark Chocolate Melt",
        weight: "",
        price: "Rs. 950",
        description: "Rich dark chocolate dessert",
        image: "/noimage.png",
        nutrition: {
          fat: "34.3g",
          protein: "7g",
          carbs: "57.2g",
          calories: "594",
        },
        tags: [
          { label: "Indulgent", icon: "🍫" },
          { label: "Dark Chocolate", icon: "🖤" },
        ],
        bgColor: "from-amber-900 via-amber-800 to-red-800",
        accentColor: "bg-amber-800",
      },
      {
        id: "fruity-curd",
        name: "Fruity Curd",
        weight: "",
        price: "Rs. 750",
        description: "Fresh fruit with creamy curd",
        image: "/noimage.png",
        nutrition: {
          fat: "11.9g",
          protein: "7.1g",
          carbs: "26.1g",
          calories: "240",
        },
        tags: [
          { label: "Fresh Fruit", icon: "🍓" },
          { label: "Light", icon: "☁️" },
        ],
        bgColor: "from-pink-400 via-red-400 to-orange-400",
        accentColor: "bg-pink-400",
      },
      {
        id: "chocolate-banana-parfait",
        name: "Chocolate & Banana Granola Parfait",
        weight: "",
        price: "Rs. 1100",
        description: "Layers of crunchy granola, ripe banana, creamy curd, and rich melted dark chocolate, drizzled with pure bee's honey and topped with toasted coconut chips",
        image: "/noimage.png",
        nutrition: {
          fat: "11.6g",
          protein: "9.5g",
          carbs: "40.6g",
          calories: "324",
        },
        tags: [
          { label: "Granola", icon: "🥣" },
          { label: "Honey", icon: "🍯" },
          { label: "Coconut", icon: "🥥" },
        ],
        bgColor: "from-yellow-600 via-amber-600 to-orange-600",
        accentColor: "bg-amber-600",
      },
      {
        id: "frutilicious-coco-parfait",
        name: "Frutilicious-Coco Parfait",
        weight: "",
        price: "Rs. 1100",
        description: "A vibrant medley of mango & mandarin layered with creamy curd, crunchy granola, & oats, drizzled with Bees honey and rich melted dark chocolate, finished with toasted coconut chips",
        image: "/noimage.png",
        nutrition: {
          fat: "25.7g",
          protein: "20.9g",
          carbs: "73.1g",
          calories: "544",
        },
        tags: [
          { label: "Tropical", icon: "🌴" },
          { label: "Granola", icon: "🥣" },
          { label: "Mango", icon: "🥭" },
        ],
        bgColor: "from-yellow-500 via-orange-500 to-pink-500",
        accentColor: "bg-orange-500",
      },
    ],
  },
  // ------------------------
  // Breakfast
  // ------------------------
  {
    id: "breakfast",
    name: "Breakfast",
    icon: Sun,
    products: [
      {
        id: "tropical-paradise-bowl",
        name: "Tropical Paradise Bowl",
        weight: "",
        price: "Rs. 1000",
        description: "Overnight soaked oats, topped with toasted coconut shavings, mouthwatering mango, juicy pineapple, and nutrient-packed chia seeds",
        image: "/noimage.png",
        nutrition: {
          fat: "16.4g",
          protein: "18.5g",
          carbs: "72.3g",
          calories: "554",
        },
        tags: [
          { label: "Overnight Oats", icon: "🌾" },
          { label: "Tropical", icon: "🌴" },
          { label: "Chia Seeds", icon: "🌱" },
        ],
        bgColor: "from-yellow-400 via-orange-400 to-pink-400",
        accentColor: "bg-yellow-400",
      },
      {
        id: "mango-tango-bowl",
        name: "Mango Tango Coconut Crunch Bowl",
        weight: "",
        price: "Rs. 900",
        description: "Overnight soaked oats topped with luscious sweet mango, ripe banana, delightful crunch of pumpkin seeds, sesame seeds, and nutty granola, star fruit slices & toasted coconut flakes",
        image: "/noimage.png",
        nutrition: {
          fat: "16.4g",
          protein: "17.4g",
          carbs: "74.8g",
          calories: "559",
        },
        tags: [
          { label: "Mango", icon: "🥭" },
          { label: "Crunchy", icon: "🥜" },
          { label: "Seeds", icon: "🌰" },
        ],
        bgColor: "from-yellow-500 via-orange-500 to-amber-500",
        accentColor: "bg-yellow-500",
      },
      {
        id: "avo-licious-toast",
        name: "Avo-licious Toast",
        weight: "",
        price: "Rs. 850",
        description: "Luscious avocado slices paired with creamy feta cheese and a burst of sweet pomegranate on toast",
        image: "/noimage.png",
        nutrition: {
          fat: "20.8g",
          protein: "8.2g",
          carbs: "27.8g",
          calories: "351",
        },
        tags: [
          { label: "Avocado", icon: "🥑" },
          { label: "Healthy Fats", icon: "💚" },
          { label: "Feta", icon: "🧀" },
        ],
        bgColor: "from-green-500 via-lime-400 to-yellow-400",
        accentColor: "bg-green-500",
      },
      {
        id: "fuel-up-toast",
        name: "Fuel up! Toast",
        weight: "",
        price: "Rs. 850",
        description: "Creamy feta cheese meets the crunch of almond nuts, all crowned with the natural sweetness of dates",
        image: "/noimage.png",
        nutrition: {
          fat: "9.5g",
          protein: "9.9g",
          carbs: "27.5g",
          calories: "239",
        },
        tags: [
          { label: "Almonds", icon: "🌰" },
          { label: "Dates", icon: "🍯" },
          { label: "Energy", icon: "⚡" },
        ],
        bgColor: "from-amber-600 via-orange-500 to-yellow-500",
        accentColor: "bg-amber-500",
      },
      {
        id: "supercharge-omelette",
        name: "Supercharge Omelette",
        weight: "",
        price: "Rs. 650",
        description: "A fluffy three-egg omelet folded with sautéed garlic, onion, and tomato, seasoned simply with salt and pepper for classic comfort",
        image: "/noimage.png",
        nutrition: {
          fat: "19.1g",
          protein: "17.8g",
          carbs: "6.7g",
          calories: "227",
        },
        tags: [
          { label: "High-Protein", icon: "💪" },
          { label: "Classic", icon: "🍳" },
          { label: "Three Eggs", icon: "🥚" },
        ],
        bgColor: "from-yellow-500 via-orange-400 to-red-400",
        accentColor: "bg-yellow-500",
      },
    ],
  },
];

export default categories;